# beaconforge config file


# address of the beaconcreator server
#addr: http://127.0.0.1:8080

# file path for binaries to convert into beacon
#files: []

# enable verbose output
#verbose: false

# path to the configuration file
#config: 

# connection string for the beacon server
#connectionString: 127.0.0.1:5353

# transport protocol to use for the beacon server (http, dns, tcp)
#transport: http

# build a static binary
#static: false

# compress the binary with upx
#upx: false

# compression level for upx
#upxLevel: 1

# enable beacon debug output
#debug: false