# Forge config file

# group id for the beacon
group-id: a7a1bf2e-6394-48a8-9488-aabcbcc8e9e2

# address of the gateway server
addr: https://gateway.sekyr.com

# file path for binaries to convert into beacon
#files: ["./testFiles/ls_darwin","./testFiles/ls_darwin1","./testFiles/ls_darwin2","./testFiles/ls_darwin3"]
files: ["/usr/bin/md5sum","/usr/bin/sha256sum","/usr/bin/nc","/bin/sh", "/usr/bin/crontab", "/sbin/ip","/usr/bin/wget","/sbin/apk","/bin/base64","/bin/chmod","/bin/echo","/bin/hostname","/bin/pwd", "/bin/sed", "/bin/tar","/usr/bin/id","/usr/bin/awk","/usr/bin/whoami", "/usr/bin/find"]
#files: ["/usr/bin/id"]

# enable verbose output for forge:
verbose: true
# output folder for the beacons
output: out
#Overwrite the beacons, this overrides the output flag
overwrite: true

# transport tag for the beacon
transport: icmp

# connection string for the beacon
connection-string: reporter.sekyr.com


# upx the beacon
#upx: false

# upx level for the beacon
#upx-level: 1


# debug output for the beacon
debug: false